# Generated by Django 5.2.3 on 2025-06-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
