# Generated by Django 5.2.3 on 2025-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in Progress', 'In Progress'), ('resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
